Command used to Run this container.

# kubectl run ubuntu05 --image=ubuntu --command sleep  --dry-run -o yaml > pod.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-30T20:17:17Z"
  labels:
    run: ubuntu05
  name: ubuntu05
  namespace: default
spec:
  containers:
  - command:
    - sleep
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu05
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30


